name: Deploy Next.js site to Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: yarn install # Or use npm install if you prefer npm
      
      - name: Build with Next.js
        run: yarn build # Or use npm run build if you prefer npm
      
      - name: Export static HTML
        run: yarn export # Or use npm run export if you prefer npm
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nextjs-app
          path: .next

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: nextjs-app
          path: .next

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .next
          user_name: GitHub Actions
          user_email: actions@github.com
          publish_branch: gh-pages
