name: PM Approval Pipeline

on:
  workflow_run:
    workflows: ["QA Pipeline for Next.js"]
    types:
      - completed

jobs:
  pm_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Request PM Approval
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          to: ${{ secrets.PM_EMAIL }}
          subject: 'PM Approval Request'
          body: 'QA has approved the changes. Please review and give your PM approval.'

      - name: Wait for PM Approval
        run: |
          while [ "$(gh issue view <issue_number> -q '.state')" != "closed" ]; do sleep 60; done
      
        continue-on-error: true
